eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG